import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js! </a>
          template
        </h1>
        <br></br>

        <div>
          <h2 className={styles.subtitle}>This template includes</h2>
          <ul>
            <li>TailwindCSS</li>
            <li>Typescript</li>
            <li>
              Jest + Testing Library{' '}
              <Link className="text-blue-600" href="/testing">
                (Example)
              </Link>
            </li>
            <li>Eslint + Prettier (airbnb config)</li>
            <li>
              Comittizen + Husky + Gitmoji{' '}
              <Link className="text-blue-600" href="/considerations">
                (Considerations)
              </Link>
            </li>
          </ul>
          <br></br>
        </div>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
      </main>
    </div>
  );
}
